### ISSUE TITLE
Invalid Version: 10.3 (Debian 10.3-1.pgdg90+1).0

### ISSUE THREAD

**Issue by aaronjameslang** [db-migrate/pg#34]
Using the latest postgres docker image gives the below error

This looks like a problem with the docker image, but would be very easy to accomodate

Essentially postgres returns `{ server_version: '10.3 (Debian 10.3-1.pgdg90+1)' }` and a little `version = version.split(' ')[0]` after `index.js:72` fixes it. Or one could downgrade to `postgres:9.6`, which is what I've done.

This may be a "Won't Fix" but hopefully it'll help anyone else facing the same error

```
[ERROR] TypeError: Invalid Version: 10.3 (Debian 10.3-1.pgdg90+1).0
    at new SemVer (/Users/aaronlang/not-safe-not-fair/node_modules/semver/semver.js:305:11)
    at compare (/Users/aaronlang/not-safe-not-fair/node_modules/semver/semver.js:578:10)
    at Function.gte (/Users/aaronlang/not-safe-not-fair/node_modules/semver/semver.js:627:10)
    at Object.<anonymous> (/Users/aaronlang/not-safe-not-fair/node_modules/db-migrate-pg/index.js:176:42)
    at tryCatcher (/Users/aaronlang/not-safe-not-fair/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/aaronlang/not-safe-not-fair/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/aaronlang/not-safe-not-fair/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/aaronlang/not-safe-not-fair/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/aaronlang/not-safe-not-fair/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/aaronlang/not-safe-not-fair/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/aaronlang/not-safe-not-fair/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/aaronlang/not-safe-not-fair/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

**Comment by debanjanbasu** [comment]
Also witnessed the same issue today, can you push a pr for this?

**Comment by wzrdtales** [comment]
Should be fixed in the latest version, please let me know if it should not.
