### ISSUE TITLE
No such driver found

### ISSUE THREAD

**Issue by ViniciusTxr** [db-migrate/pg#75]
I am getting the following error in version 1.3.0:

```
     Error: No such driver found, please try to install it via npm install db-migrate-pg or npm install -g db-migrate-pg
      at Object.exports.connect (node_modules/db-migrate/lib/driver/index.js:77:11)
      at Object.exports.connect (node_modules/db-migrate/connect.js:15:10)
      at /home/vinicius/Luizalabs/Projects/fat-copy/faturamento-api/node_modules/db-migrate/lib/commands/up.js:15:13
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
```
      
Until version 1.2.2 it was working perfectly, but after new versions were published the lib is showing an error.

Any solution?

The error is not on my side (as @wzrdtales said in [issue 74](https://github.com/db-migrate/pg/issues/74)), since until yesterday in version 1.2.2 everything was working perfectly.
After the publication of the new versions (yesterday, May 4th) the library is no longer working.

My node version is v12.22.12

**Comment by ViniciusTxr** [comment]
A temporary solution (until they fix the lib) for those who have the same problem as me:

**Fixing version 1.2.2 in your package.json will solve**

**Comment by wzrdtales** [comment]
not reproducible. `1.3.0` perfectly fine loads. please provide a fully reproducible project.

further its impossible that the version change causes this. the change was literally this:

https://github.com/db-migrate/pg/commit/24e231e01adf50cf260636cd50212d91e137b49d

and nothing else. This can't cause your described issues.

**Comment by wzrdtales** [comment]
closed https://github.com/db-migrate/pg/issues/74#issuecomment-1535494402
